import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { classNames } from "@/utils";
import Navbar from "@/components/Navbar";
import { Headline, Text } from "@/components/Typography";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames("tw-h-full", "tw-text-default", inter.className)}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
