#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Styling, testing and building your project before committing'
cd packages/frontend/

# Check Prettier standards
npm run format && npm run check-format ||
(
   echo '❌❌❌  Your formatting is raw ❌❌❌
   Run "npm run format" script.
   Prettier Check Failed. Run npm run format, add changes and try commit again.';
   false;
)

# Check ESLint Standards
npm run lint &&npm run check-lint ||
(
   echo '❌❌❌ Your code style is incoherent ❌❌❌ 
   Run "npm run lint" script.
   ESLint Check Failed. Run npm lint and make the required changes listed above, add changes and try to commit again.'
   false; 
)

# Check tsconfig standards
npm run check-types ||
(
   echo '❌❌❌ Failed Type check. ❌❌❌
   Make the changes required above.'
   false;
)

# If everything passes... Now we can commit
echo '⚙️⚙️⚙️ Code looks good. Trying to build now... ⚙️⚙️⚙️'

npm run build ||
(
   echo '❌❌❌ Your build failed ❌❌❌.
   Run "npm run build" script.
   React build failed: View the errors above to see why. '
   false;
)

# If everything passes... Now we can commit
echo '✅✅✅ All scripts succedded. Committing this now. ✅✅✅'